package regression;
import org.safs.model.Component;
import org.safs.model.tools.RuntimeDataAware;
import org.safs.tools.RuntimeDataInterface;

/** *** DO NOT EDIT THIS FILE ***<br>
    THIS FILE IS GENERATED AUTOMATICALLY by org.safs.model.tools.ComponentGenerator!<br><p>
    A JSAFS AppMap reference for SAFS App Map: 'C:\Repository\cvshome\git\SAFS\SAFSPlus-REGRESSION\Maps' */
public final class Map implements RuntimeDataAware {

    private static RuntimeDataInterface dataInterface = null;

    /** Called internally as part of the bootstrap process of Dependency Injection. */
    public void setRuntimeDataInterface(RuntimeDataInterface helper){
        dataInterface = helper;
    }

    // The Names of ApplicationConstants:

    /** "DOJO_CHART_URL" */
    public static final String DOJO_CHART_URL = "DOJO_CHART_URL";

    /** The resolved runtime value of constant 'DOJO_CHART_URL', or null. */
    public static String DOJO_CHART_URL(){
        try{ return dataInterface.getVariable("DOJO_CHART_URL"); }
        catch(Exception x){ return null; }
    }

    /** "W3CConfirmURL" */
    public static final String W3CConfirmURL = "W3CConfirmURL";

    /** The resolved runtime value of constant 'W3CConfirmURL', or null. */
    public static String W3CConfirmURL(){
        try{ return dataInterface.getVariable("W3CConfirmURL"); }
        catch(Exception x){ return null; }
    }

    /** "GOJS_MINIMAL_URL" */
    public static final String GOJS_MINIMAL_URL = "GOJS_MINIMAL_URL";

    /** The resolved runtime value of constant 'GOJS_MINIMAL_URL', or null. */
    public static String GOJS_MINIMAL_URL(){
        try{ return dataInterface.getVariable("GOJS_MINIMAL_URL"); }
        catch(Exception x){ return null; }
    }

    /** "THOMAS_BAYER_SQLREST_PRODUCT_URL" */
    public static final String THOMAS_BAYER_SQLREST_PRODUCT_URL = "THOMAS_BAYER_SQLREST_PRODUCT_URL";

    /** The resolved runtime value of constant 'THOMAS_BAYER_SQLREST_PRODUCT_URL', or null. */
    public static String THOMAS_BAYER_SQLREST_PRODUCT_URL(){
        try{ return dataInterface.getVariable("THOMAS_BAYER_SQLREST_PRODUCT_URL"); }
        catch(Exception x){ return null; }
    }

    /** "THOMAS_BAYER_SQLREST_INVOICE_URL" */
    public static final String THOMAS_BAYER_SQLREST_INVOICE_URL = "THOMAS_BAYER_SQLREST_INVOICE_URL";

    /** The resolved runtime value of constant 'THOMAS_BAYER_SQLREST_INVOICE_URL', or null. */
    public static String THOMAS_BAYER_SQLREST_INVOICE_URL(){
        try{ return dataInterface.getVariable("THOMAS_BAYER_SQLREST_INVOICE_URL"); }
        catch(Exception x){ return null; }
    }

    /** "HtmlLinkTargetPageURL" */
    public static final String HtmlLinkTargetPageURL = "HtmlLinkTargetPageURL";

    /** The resolved runtime value of constant 'HtmlLinkTargetPageURL', or null. */
    public static String HtmlLinkTargetPageURL(){
        try{ return dataInterface.getVariable("HtmlLinkTargetPageURL"); }
        catch(Exception x){ return null; }
    }

    /** "THOMAS_BAYER_SQLREST_ITEM_URL" */
    public static final String THOMAS_BAYER_SQLREST_ITEM_URL = "THOMAS_BAYER_SQLREST_ITEM_URL";

    /** The resolved runtime value of constant 'THOMAS_BAYER_SQLREST_ITEM_URL', or null. */
    public static String THOMAS_BAYER_SQLREST_ITEM_URL(){
        try{ return dataInterface.getVariable("THOMAS_BAYER_SQLREST_ITEM_URL"); }
        catch(Exception x){ return null; }
    }

    /** "W3CAlertURL" */
    public static final String W3CAlertURL = "W3CAlertURL";

    /** The resolved runtime value of constant 'W3CAlertURL', or null. */
    public static String W3CAlertURL(){
        try{ return dataInterface.getVariable("W3CAlertURL"); }
        catch(Exception x){ return null; }
    }

    /** "InternalSecondPageURL" */
    public static final String InternalSecondPageURL = "InternalSecondPageURL";

    /** The resolved runtime value of constant 'InternalSecondPageURL', or null. */
    public static String InternalSecondPageURL(){
        try{ return dataInterface.getVariable("InternalSecondPageURL"); }
        catch(Exception x){ return null; }
    }

    /** "W3CPromptURL" */
    public static final String W3CPromptURL = "W3CPromptURL";

    /** The resolved runtime value of constant 'W3CPromptURL', or null. */
    public static String W3CPromptURL(){
        try{ return dataInterface.getVariable("W3CPromptURL"); }
        catch(Exception x){ return null; }
    }

    /** "THOMAS_BAYER_URL" */
    public static final String THOMAS_BAYER_URL = "THOMAS_BAYER_URL";

    /** The resolved runtime value of constant 'THOMAS_BAYER_URL', or null. */
    public static String THOMAS_BAYER_URL(){
        try{ return dataInterface.getVariable("THOMAS_BAYER_URL"); }
        catch(Exception x){ return null; }
    }

    /** "THOMAS_BAYER_SQLREST_CUSTOMER_URL" */
    public static final String THOMAS_BAYER_SQLREST_CUSTOMER_URL = "THOMAS_BAYER_SQLREST_CUSTOMER_URL";

    /** The resolved runtime value of constant 'THOMAS_BAYER_SQLREST_CUSTOMER_URL', or null. */
    public static String THOMAS_BAYER_SQLREST_CUSTOMER_URL(){
        try{ return dataInterface.getVariable("THOMAS_BAYER_SQLREST_CUSTOMER_URL"); }
        catch(Exception x){ return null; }
    }

    /** "InternalTestLinkPageURL" */
    public static final String InternalTestLinkPageURL = "InternalTestLinkPageURL";

    /** The resolved runtime value of constant 'InternalTestLinkPageURL', or null. */
    public static String InternalTestLinkPageURL(){
        try{ return dataInterface.getVariable("InternalTestLinkPageURL"); }
        catch(Exception x){ return null; }
    }

    /** "THOMAS_BAYER_SQLREST_URL" */
    public static final String THOMAS_BAYER_SQLREST_URL = "THOMAS_BAYER_SQLREST_URL";

    /** The resolved runtime value of constant 'THOMAS_BAYER_SQLREST_URL', or null. */
    public static String THOMAS_BAYER_SQLREST_URL(){
        try{ return dataInterface.getVariable("THOMAS_BAYER_SQLREST_URL"); }
        catch(Exception x){ return null; }
    }

    /** "URL_SAS_FOLDER" */
    public static final String URL_SAS_FOLDER = "URL_SAS_FOLDER";

    /** The resolved runtime value of constant 'URL_SAS_FOLDER', or null. */
    public static String URL_SAS_FOLDER(){
        try{ return dataInterface.getVariable("URL_SAS_FOLDER"); }
        catch(Exception x){ return null; }
    }

    /** "payload2" */
    public static final String payload2 = "payload2";

    /** The resolved runtime value of constant 'payload2', or null. */
    public static String payload2(){
        try{ return dataInterface.getVariable("payload2"); }
        catch(Exception x){ return null; }
    }

    /** "networkConditions" */
    public static final String networkConditions = "networkConditions";

    /** The resolved runtime value of constant 'networkConditions', or null. */
    public static String networkConditions(){
        try{ return dataInterface.getVariable("networkConditions"); }
        catch(Exception x){ return null; }
    }

    /** "payload" */
    public static final String payload = "payload";

    /** The resolved runtime value of constant 'payload', or null. */
    public static String payload(){
        try{ return dataInterface.getVariable("payload"); }
        catch(Exception x){ return null; }
    }

    /** "networkConditionsSlow" */
    public static final String networkConditionsSlow = "networkConditionsSlow";

    /** The resolved runtime value of constant 'networkConditionsSlow', or null. */
    public static String networkConditionsSlow(){
        try{ return dataInterface.getVariable("networkConditionsSlow"); }
        catch(Exception x){ return null; }
    }

    /** "GoogleURL" */
    public static final String GoogleURL = "GoogleURL";

    /** The resolved runtime value of constant 'GoogleURL', or null. */
    public static String GoogleURL(){
        try{ return dataInterface.getVariable("GoogleURL"); }
        catch(Exception x){ return null; }
    }

    /** "TestBrowserName" */
    public static final String TestBrowserName = "TestBrowserName";

    /** The resolved runtime value of constant 'TestBrowserName', or null. */
    public static String TestBrowserName(){
        try{ return dataInterface.getVariable("TestBrowserName"); }
        catch(Exception x){ return null; }
    }

    /** "ID_RESPONSE_CUSTOMER_HEADER" */
    public static final String ID_RESPONSE_CUSTOMER_HEADER = "ID_RESPONSE_CUSTOMER_HEADER";

    /** The resolved runtime value of constant 'ID_RESPONSE_CUSTOMER_HEADER', or null. */
    public static String ID_RESPONSE_CUSTOMER_HEADER(){
        try{ return dataInterface.getVariable("ID_RESPONSE_CUSTOMER_HEADER"); }
        catch(Exception x){ return null; }
    }

    /** "AUTH_MARK_SAS_FOLDER_OAUTH2" */
    public static final String AUTH_MARK_SAS_FOLDER_OAUTH2 = "AUTH_MARK_SAS_FOLDER_OAUTH2";

    /** The resolved runtime value of constant 'AUTH_MARK_SAS_FOLDER_OAUTH2', or null. */
    public static String AUTH_MARK_SAS_FOLDER_OAUTH2(){
        try{ return dataInterface.getVariable("AUTH_MARK_SAS_FOLDER_OAUTH2"); }
        catch(Exception x){ return null; }
    }

    /** "VAR_PRODUCT_PUT" */
    public static final String VAR_PRODUCT_PUT = "VAR_PRODUCT_PUT";

    /** The resolved runtime value of constant 'VAR_PRODUCT_PUT', or null. */
    public static String VAR_PRODUCT_PUT(){
        try{ return dataInterface.getVariable("VAR_PRODUCT_PUT"); }
        catch(Exception x){ return null; }
    }

    /** "AUTH_MARK_SIMPLE" */
    public static final String AUTH_MARK_SIMPLE = "AUTH_MARK_SIMPLE";

    /** The resolved runtime value of constant 'AUTH_MARK_SIMPLE', or null. */
    public static String AUTH_MARK_SIMPLE(){
        try{ return dataInterface.getVariable("AUTH_MARK_SIMPLE"); }
        catch(Exception x){ return null; }
    }

    /** "PRODUCT_PUT" */
    public static final String PRODUCT_PUT = "PRODUCT_PUT";

    /** The resolved runtime value of constant 'PRODUCT_PUT', or null. */
    public static String PRODUCT_PUT(){
        try{ return dataInterface.getVariable("PRODUCT_PUT"); }
        catch(Exception x){ return null; }
    }

    /** "BODY_PRODUCT_PUT" */
    public static final String BODY_PRODUCT_PUT = "BODY_PRODUCT_PUT";

    /** The resolved runtime value of constant 'BODY_PRODUCT_PUT', or null. */
    public static String BODY_PRODUCT_PUT(){
        try{ return dataInterface.getVariable("BODY_PRODUCT_PUT"); }
        catch(Exception x){ return null; }
    }

    /** "FOLDER_GET" */
    public static final String FOLDER_GET = "FOLDER_GET";

    /** The resolved runtime value of constant 'FOLDER_GET', or null. */
    public static String FOLDER_GET(){
        try{ return dataInterface.getVariable("FOLDER_GET"); }
        catch(Exception x){ return null; }
    }

    /** "PATH_CUSTOMER" */
    public static final String PATH_CUSTOMER = "PATH_CUSTOMER";

    /** The resolved runtime value of constant 'PATH_CUSTOMER', or null. */
    public static String PATH_CUSTOMER(){
        try{ return dataInterface.getVariable("PATH_CUSTOMER"); }
        catch(Exception x){ return null; }
    }

    /** "VAR_FOLDER_GET" */
    public static final String VAR_FOLDER_GET = "VAR_FOLDER_GET";

    /** The resolved runtime value of constant 'VAR_FOLDER_GET', or null. */
    public static String VAR_FOLDER_GET(){
        try{ return dataInterface.getVariable("VAR_FOLDER_GET"); }
        catch(Exception x){ return null; }
    }

    /** "ID_RESPONSE_FOLDER_GET" */
    public static final String ID_RESPONSE_FOLDER_GET = "ID_RESPONSE_FOLDER_GET";

    /** The resolved runtime value of constant 'ID_RESPONSE_FOLDER_GET', or null. */
    public static String ID_RESPONSE_FOLDER_GET(){
        try{ return dataInterface.getVariable("ID_RESPONSE_FOLDER_GET"); }
        catch(Exception x){ return null; }
    }

    /** "URL_BAYER_SQLREST" */
    public static final String URL_BAYER_SQLREST = "URL_BAYER_SQLREST";

    /** The resolved runtime value of constant 'URL_BAYER_SQLREST', or null. */
    public static String URL_BAYER_SQLREST(){
        try{ return dataInterface.getVariable("URL_BAYER_SQLREST"); }
        catch(Exception x){ return null; }
    }

    /** "PATH_PRODUCT_N" */
    public static final String PATH_PRODUCT_N = "PATH_PRODUCT_N";

    /** The resolved runtime value of constant 'PATH_PRODUCT_N', or null. */
    public static String PATH_PRODUCT_N(){
        try{ return dataInterface.getVariable("PATH_PRODUCT_N"); }
        catch(Exception x){ return null; }
    }

    /** "CUSTOMER_HEADER" */
    public static final String CUSTOMER_HEADER = "CUSTOMER_HEADER";

    /** The resolved runtime value of constant 'CUSTOMER_HEADER', or null. */
    public static String CUSTOMER_HEADER(){
        try{ return dataInterface.getVariable("CUSTOMER_HEADER"); }
        catch(Exception x){ return null; }
    }

    /** "AUTH_MARK_OAUTH2" */
    public static final String AUTH_MARK_OAUTH2 = "AUTH_MARK_OAUTH2";

    /** The resolved runtime value of constant 'AUTH_MARK_OAUTH2', or null. */
    public static String AUTH_MARK_OAUTH2(){
        try{ return dataInterface.getVariable("AUTH_MARK_OAUTH2"); }
        catch(Exception x){ return null; }
    }

    /** "ID_RESPONSE_PRODUCT_PUT" */
    public static final String ID_RESPONSE_PRODUCT_PUT = "ID_RESPONSE_PRODUCT_PUT";

    /** The resolved runtime value of constant 'ID_RESPONSE_PRODUCT_PUT', or null. */
    public static String ID_RESPONSE_PRODUCT_PUT(){
        try{ return dataInterface.getVariable("ID_RESPONSE_PRODUCT_PUT"); }
        catch(Exception x){ return null; }
    }

    /** "CUSTOMER_GET" */
    public static final String CUSTOMER_GET = "CUSTOMER_GET";

    /** The resolved runtime value of constant 'CUSTOMER_GET', or null. */
    public static String CUSTOMER_GET(){
        try{ return dataInterface.getVariable("CUSTOMER_GET"); }
        catch(Exception x){ return null; }
    }

    /** "PROCUCT_N" */
    public static final String PROCUCT_N = "PROCUCT_N";

    /** The resolved runtime value of constant 'PROCUCT_N', or null. */
    public static String PROCUCT_N(){
        try{ return dataInterface.getVariable("PROCUCT_N"); }
        catch(Exception x){ return null; }
    }

    /** "PATH_ROOTFolders" */
    public static final String PATH_ROOTFolders = "PATH_ROOTFolders";

    /** The resolved runtime value of constant 'PATH_ROOTFolders', or null. */
    public static String PATH_ROOTFolders(){
        try{ return dataInterface.getVariable("PATH_ROOTFolders"); }
        catch(Exception x){ return null; }
    }

    /** "VAR_CUSTOMER_HEADER" */
    public static final String VAR_CUSTOMER_HEADER = "VAR_CUSTOMER_HEADER";

    /** The resolved runtime value of constant 'VAR_CUSTOMER_HEADER', or null. */
    public static String VAR_CUSTOMER_HEADER(){
        try{ return dataInterface.getVariable("VAR_CUSTOMER_HEADER"); }
        catch(Exception x){ return null; }
    }

    /** "VAR_CUSTOMER_GET" */
    public static final String VAR_CUSTOMER_GET = "VAR_CUSTOMER_GET";

    /** The resolved runtime value of constant 'VAR_CUSTOMER_GET', or null. */
    public static String VAR_CUSTOMER_GET(){
        try{ return dataInterface.getVariable("VAR_CUSTOMER_GET"); }
        catch(Exception x){ return null; }
    }

    /** "ID_RESPONSE_CUSTOMER_GET" */
    public static final String ID_RESPONSE_CUSTOMER_GET = "ID_RESPONSE_CUSTOMER_GET";

    /** The resolved runtime value of constant 'ID_RESPONSE_CUSTOMER_GET', or null. */
    public static String ID_RESPONSE_CUSTOMER_GET(){
        try{ return dataInterface.getVariable("ID_RESPONSE_CUSTOMER_GET"); }
        catch(Exception x){ return null; }
    }

    /** "HEADER_PRODUCT_PUT" */
    public static final String HEADER_PRODUCT_PUT = "HEADER_PRODUCT_PUT";

    /** The resolved runtime value of constant 'HEADER_PRODUCT_PUT', or null. */
    public static String HEADER_PRODUCT_PUT(){
        try{ return dataInterface.getVariable("HEADER_PRODUCT_PUT"); }
        catch(Exception x){ return null; }
    }

    /** "subarea" */
    public static final String subarea = "subarea";

    /** The resolved runtime value of constant 'subarea', or null. */
    public static String subarea(){
        try{ return dataInterface.getVariable("subarea"); }
        catch(Exception x){ return null; }
    }

    /** "Tab_jtable2" */
    public static final String Tab_jtable2 = "Tab_jtable2";

    /** The resolved runtime value of constant 'Tab_jtable2', or null. */
    public static String Tab_jtable2(){
        try{ return dataInterface.getVariable("Tab_jtable2"); }
        catch(Exception x){ return null; }
    }

    /** "Tab_jtable" */
    public static final String Tab_jtable = "Tab_jtable";

    /** The resolved runtime value of constant 'Tab_jtable', or null. */
    public static String Tab_jtable(){
        try{ return dataInterface.getVariable("Tab_jtable"); }
        catch(Exception x){ return null; }
    }

    /** "FilteredAreas2" */
    public static final String FilteredAreas2 = "FilteredAreas2";

    /** The resolved runtime value of constant 'FilteredAreas2', or null. */
    public static String FilteredAreas2(){
        try{ return dataInterface.getVariable("FilteredAreas2"); }
        catch(Exception x){ return null; }
    }

    /** "FilteredAreas1" */
    public static final String FilteredAreas1 = "FilteredAreas1";

    /** The resolved runtime value of constant 'FilteredAreas1', or null. */
    public static String FilteredAreas1(){
        try{ return dataInterface.getVariable("FilteredAreas1"); }
        catch(Exception x){ return null; }
    }

    /** "Tab_mort_calc" */
    public static final String Tab_mort_calc = "Tab_mort_calc";

    /** The resolved runtime value of constant 'Tab_mort_calc', or null. */
    public static String Tab_mort_calc(){
        try{ return dataInterface.getVariable("Tab_mort_calc"); }
        catch(Exception x){ return null; }
    }

    /** "LocationKey" */
    public static final String LocationKey = "LocationKey";

    /** The resolved runtime value of constant 'LocationKey', or null. */
    public static String LocationKey(){
        try{ return dataInterface.getVariable("LocationKey"); }
        catch(Exception x){ return null; }
    }

    /** "locationA" */
    public static final String locationA = "locationA";

    /** The resolved runtime value of constant 'locationA', or null. */
    public static String locationA(){
        try{ return dataInterface.getVariable("locationA"); }
        catch(Exception x){ return null; }
    }

    /** "SAPDemoURL" */
    public static final String SAPDemoURL = "SAPDemoURL";

    /** The resolved runtime value of constant 'SAPDemoURL', or null. */
    public static String SAPDemoURL(){
        try{ return dataInterface.getVariable("SAPDemoURL"); }
        catch(Exception x){ return null; }
    }

    /** "Tab_jtree" */
    public static final String Tab_jtree = "Tab_jtree";

    /** The resolved runtime value of constant 'Tab_jtree', or null. */
    public static String Tab_jtree(){
        try{ return dataInterface.getVariable("Tab_jtree"); }
        catch(Exception x){ return null; }
    }

    /** "Tab_jpan" */
    public static final String Tab_jpan = "Tab_jpan";

    /** The resolved runtime value of constant 'Tab_jpan', or null. */
    public static String Tab_jpan(){
        try{ return dataInterface.getVariable("Tab_jpan"); }
        catch(Exception x){ return null; }
    }

    /** "Tab_basc_comp" */
    public static final String Tab_basc_comp = "Tab_basc_comp";

    /** The resolved runtime value of constant 'Tab_basc_comp', or null. */
    public static String Tab_basc_comp(){
        try{ return dataInterface.getVariable("Tab_basc_comp"); }
        catch(Exception x){ return null; }
    }

    /** "Tab_jtree2" */
    public static final String Tab_jtree2 = "Tab_jtree2";

    /** The resolved runtime value of constant 'Tab_jtree2', or null. */
    public static String Tab_jtree2(){
        try{ return dataInterface.getVariable("Tab_jtree2"); }
        catch(Exception x){ return null; }
    }

    // The Names of Window and Child Component objects: 

    /** "BAYERREST" Component and its children. */
    public static class BAYERREST {

        // No use for a default constructor.
        private BAYERREST(){}

        /** "BAYERREST" Window Component itself. */
        public static final Component BAYERREST = new Component("BAYERREST");

        /** "BAYERSERVICE002" Component in "BAYERREST". */
        public static final Component BAYERSERVICE002 = new Component(BAYERREST, "BAYERSERVICE002");

        /** "BAYERSERVICE001" Component in "BAYERREST". */
        public static final Component BAYERSERVICE001 = new Component(BAYERREST, "BAYERSERVICE001");
    }

    /** "ApplicationConstants" Component and its children. */
    public static class ApplicationConstants {

        // No use for a default constructor.
        private ApplicationConstants(){}

        /** "ApplicationConstants" Window Component itself. */
        public static final Component ApplicationConstants = new Component("ApplicationConstants");

        /** "DOJO_CHART_URL" Component in "ApplicationConstants". */
        public static final Component DOJO_CHART_URL = new Component(ApplicationConstants, "DOJO_CHART_URL");

        /** "W3CConfirmURL" Component in "ApplicationConstants". */
        public static final Component W3CConfirmURL = new Component(ApplicationConstants, "W3CConfirmURL");

        /** "GOJS_MINIMAL_URL" Component in "ApplicationConstants". */
        public static final Component GOJS_MINIMAL_URL = new Component(ApplicationConstants, "GOJS_MINIMAL_URL");

        /** "THOMAS_BAYER_SQLREST_PRODUCT_URL" Component in "ApplicationConstants". */
        public static final Component THOMAS_BAYER_SQLREST_PRODUCT_URL = new Component(ApplicationConstants, "THOMAS_BAYER_SQLREST_PRODUCT_URL");

        /** "THOMAS_BAYER_SQLREST_INVOICE_URL" Component in "ApplicationConstants". */
        public static final Component THOMAS_BAYER_SQLREST_INVOICE_URL = new Component(ApplicationConstants, "THOMAS_BAYER_SQLREST_INVOICE_URL");

        /** "HtmlLinkTargetPageURL" Component in "ApplicationConstants". */
        public static final Component HtmlLinkTargetPageURL = new Component(ApplicationConstants, "HtmlLinkTargetPageURL");

        /** "THOMAS_BAYER_SQLREST_ITEM_URL" Component in "ApplicationConstants". */
        public static final Component THOMAS_BAYER_SQLREST_ITEM_URL = new Component(ApplicationConstants, "THOMAS_BAYER_SQLREST_ITEM_URL");

        /** "W3CAlertURL" Component in "ApplicationConstants". */
        public static final Component W3CAlertURL = new Component(ApplicationConstants, "W3CAlertURL");

        /** "InternalSecondPageURL" Component in "ApplicationConstants". */
        public static final Component InternalSecondPageURL = new Component(ApplicationConstants, "InternalSecondPageURL");

        /** "W3CPromptURL" Component in "ApplicationConstants". */
        public static final Component W3CPromptURL = new Component(ApplicationConstants, "W3CPromptURL");

        /** "THOMAS_BAYER_URL" Component in "ApplicationConstants". */
        public static final Component THOMAS_BAYER_URL = new Component(ApplicationConstants, "THOMAS_BAYER_URL");

        /** "THOMAS_BAYER_SQLREST_CUSTOMER_URL" Component in "ApplicationConstants". */
        public static final Component THOMAS_BAYER_SQLREST_CUSTOMER_URL = new Component(ApplicationConstants, "THOMAS_BAYER_SQLREST_CUSTOMER_URL");

        /** "InternalTestLinkPageURL" Component in "ApplicationConstants". */
        public static final Component InternalTestLinkPageURL = new Component(ApplicationConstants, "InternalTestLinkPageURL");

        /** "THOMAS_BAYER_SQLREST_URL" Component in "ApplicationConstants". */
        public static final Component THOMAS_BAYER_SQLREST_URL = new Component(ApplicationConstants, "THOMAS_BAYER_SQLREST_URL");

        /** "URL_SAS_FOLDER" Component in "ApplicationConstants". */
        public static final Component URL_SAS_FOLDER = new Component(ApplicationConstants, "URL_SAS_FOLDER");

        /** "payload2" Component in "ApplicationConstants". */
        public static final Component payload2 = new Component(ApplicationConstants, "payload2");

        /** "networkConditions" Component in "ApplicationConstants". */
        public static final Component networkConditions = new Component(ApplicationConstants, "networkConditions");

        /** "payload" Component in "ApplicationConstants". */
        public static final Component payload = new Component(ApplicationConstants, "payload");

        /** "networkConditionsSlow" Component in "ApplicationConstants". */
        public static final Component networkConditionsSlow = new Component(ApplicationConstants, "networkConditionsSlow");

        /** "GoogleURL" Component in "ApplicationConstants". */
        public static final Component GoogleURL = new Component(ApplicationConstants, "GoogleURL");

        /** "TestBrowserName" Component in "ApplicationConstants". */
        public static final Component TestBrowserName = new Component(ApplicationConstants, "TestBrowserName");

        /** "ID_RESPONSE_CUSTOMER_HEADER" Component in "ApplicationConstants". */
        public static final Component ID_RESPONSE_CUSTOMER_HEADER = new Component(ApplicationConstants, "ID_RESPONSE_CUSTOMER_HEADER");

        /** "AUTH_MARK_SAS_FOLDER_OAUTH2" Component in "ApplicationConstants". */
        public static final Component AUTH_MARK_SAS_FOLDER_OAUTH2 = new Component(ApplicationConstants, "AUTH_MARK_SAS_FOLDER_OAUTH2");

        /** "VAR_PRODUCT_PUT" Component in "ApplicationConstants". */
        public static final Component VAR_PRODUCT_PUT = new Component(ApplicationConstants, "VAR_PRODUCT_PUT");

        /** "AUTH_MARK_SIMPLE" Component in "ApplicationConstants". */
        public static final Component AUTH_MARK_SIMPLE = new Component(ApplicationConstants, "AUTH_MARK_SIMPLE");

        /** "PRODUCT_PUT" Component in "ApplicationConstants". */
        public static final Component PRODUCT_PUT = new Component(ApplicationConstants, "PRODUCT_PUT");

        /** "BODY_PRODUCT_PUT" Component in "ApplicationConstants". */
        public static final Component BODY_PRODUCT_PUT = new Component(ApplicationConstants, "BODY_PRODUCT_PUT");

        /** "FOLDER_GET" Component in "ApplicationConstants". */
        public static final Component FOLDER_GET = new Component(ApplicationConstants, "FOLDER_GET");

        /** "PATH_CUSTOMER" Component in "ApplicationConstants". */
        public static final Component PATH_CUSTOMER = new Component(ApplicationConstants, "PATH_CUSTOMER");

        /** "VAR_FOLDER_GET" Component in "ApplicationConstants". */
        public static final Component VAR_FOLDER_GET = new Component(ApplicationConstants, "VAR_FOLDER_GET");

        /** "ID_RESPONSE_FOLDER_GET" Component in "ApplicationConstants". */
        public static final Component ID_RESPONSE_FOLDER_GET = new Component(ApplicationConstants, "ID_RESPONSE_FOLDER_GET");

        /** "URL_BAYER_SQLREST" Component in "ApplicationConstants". */
        public static final Component URL_BAYER_SQLREST = new Component(ApplicationConstants, "URL_BAYER_SQLREST");

        /** "PATH_PRODUCT_N" Component in "ApplicationConstants". */
        public static final Component PATH_PRODUCT_N = new Component(ApplicationConstants, "PATH_PRODUCT_N");

        /** "CUSTOMER_HEADER" Component in "ApplicationConstants". */
        public static final Component CUSTOMER_HEADER = new Component(ApplicationConstants, "CUSTOMER_HEADER");

        /** "AUTH_MARK_OAUTH2" Component in "ApplicationConstants". */
        public static final Component AUTH_MARK_OAUTH2 = new Component(ApplicationConstants, "AUTH_MARK_OAUTH2");

        /** "ID_RESPONSE_PRODUCT_PUT" Component in "ApplicationConstants". */
        public static final Component ID_RESPONSE_PRODUCT_PUT = new Component(ApplicationConstants, "ID_RESPONSE_PRODUCT_PUT");

        /** "CUSTOMER_GET" Component in "ApplicationConstants". */
        public static final Component CUSTOMER_GET = new Component(ApplicationConstants, "CUSTOMER_GET");

        /** "PROCUCT_N" Component in "ApplicationConstants". */
        public static final Component PROCUCT_N = new Component(ApplicationConstants, "PROCUCT_N");

        /** "PATH_ROOTFolders" Component in "ApplicationConstants". */
        public static final Component PATH_ROOTFolders = new Component(ApplicationConstants, "PATH_ROOTFolders");

        /** "VAR_CUSTOMER_HEADER" Component in "ApplicationConstants". */
        public static final Component VAR_CUSTOMER_HEADER = new Component(ApplicationConstants, "VAR_CUSTOMER_HEADER");

        /** "VAR_CUSTOMER_GET" Component in "ApplicationConstants". */
        public static final Component VAR_CUSTOMER_GET = new Component(ApplicationConstants, "VAR_CUSTOMER_GET");

        /** "ID_RESPONSE_CUSTOMER_GET" Component in "ApplicationConstants". */
        public static final Component ID_RESPONSE_CUSTOMER_GET = new Component(ApplicationConstants, "ID_RESPONSE_CUSTOMER_GET");

        /** "HEADER_PRODUCT_PUT" Component in "ApplicationConstants". */
        public static final Component HEADER_PRODUCT_PUT = new Component(ApplicationConstants, "HEADER_PRODUCT_PUT");

        /** "subarea" Component in "ApplicationConstants". */
        public static final Component subarea = new Component(ApplicationConstants, "subarea");

        /** "Tab_jtable2" Component in "ApplicationConstants". */
        public static final Component Tab_jtable2 = new Component(ApplicationConstants, "Tab_jtable2");

        /** "Tab_jtable" Component in "ApplicationConstants". */
        public static final Component Tab_jtable = new Component(ApplicationConstants, "Tab_jtable");

        /** "FilteredAreas2" Component in "ApplicationConstants". */
        public static final Component FilteredAreas2 = new Component(ApplicationConstants, "FilteredAreas2");

        /** "FilteredAreas1" Component in "ApplicationConstants". */
        public static final Component FilteredAreas1 = new Component(ApplicationConstants, "FilteredAreas1");

        /** "Tab_mort_calc" Component in "ApplicationConstants". */
        public static final Component Tab_mort_calc = new Component(ApplicationConstants, "Tab_mort_calc");

        /** "LocationKey" Component in "ApplicationConstants". */
        public static final Component LocationKey = new Component(ApplicationConstants, "LocationKey");

        /** "locationA" Component in "ApplicationConstants". */
        public static final Component locationA = new Component(ApplicationConstants, "locationA");

        /** "SAPDemoURL" Component in "ApplicationConstants". */
        public static final Component SAPDemoURL = new Component(ApplicationConstants, "SAPDemoURL");

        /** "Tab_jtree" Component in "ApplicationConstants". */
        public static final Component Tab_jtree = new Component(ApplicationConstants, "Tab_jtree");

        /** "Tab_jpan" Component in "ApplicationConstants". */
        public static final Component Tab_jpan = new Component(ApplicationConstants, "Tab_jpan");

        /** "Tab_basc_comp" Component in "ApplicationConstants". */
        public static final Component Tab_basc_comp = new Component(ApplicationConstants, "Tab_basc_comp");

        /** "Tab_jtree2" Component in "ApplicationConstants". */
        public static final Component Tab_jtree2 = new Component(ApplicationConstants, "Tab_jtree2");
    }

    /** "ThomasBayerPage" Component and its children. */
    public static class ThomasBayerPage {

        // No use for a default constructor.
        private ThomasBayerPage(){}

        /** "ThomasBayerPage" Window Component itself. */
        public static final Component ThomasBayerPage = new Component("ThomasBayerPage");
    }

    /** "SASFolderREST" Component and its children. */
    public static class SASFolderREST {

        // No use for a default constructor.
        private SASFolderREST(){}

        /** "SASFolderREST" Window Component itself. */
        public static final Component SASFolderREST = new Component("SASFolderREST");

        /** "SASFolderService001" Component in "SASFolderREST". */
        public static final Component SASFolderService001 = new Component(SASFolderREST, "SASFolderService001");
    }

    /** "HtmlLinkTargetPage" Component and its children. */
    public static class HtmlLinkTargetPage {

        // No use for a default constructor.
        private HtmlLinkTargetPage(){}

        /** "HtmlLinkTargetPage" Window Component itself. */
        public static final Component HtmlLinkTargetPage = new Component("HtmlLinkTargetPage");

        /** "Link" Component in "HtmlLinkTargetPage". */
        public static final Component Link = new Component(HtmlLinkTargetPage, "Link");

        /** "Body" Component in "HtmlLinkTargetPage". */
        public static final Component Body = new Component(HtmlLinkTargetPage, "Body");
    }

    /** "Google" Component and its children. */
    public static class Google {

        // No use for a default constructor.
        private Google(){}

        /** "Google" Window Component itself. */
        public static final Component Google = new Component("Google");
    }

    /** "JavaDemo" Component and its children. */
    public static class JavaDemo {

        // No use for a default constructor.
        private JavaDemo(){}

        /** "JavaDemo" Window Component itself. */
        public static final Component JavaDemo = new Component("JavaDemo");

        /** "DataGrid" Component in "JavaDemo". */
        public static final Component DataGrid = new Component(JavaDemo, "DataGrid");

        /** "Label" Component in "JavaDemo". */
        public static final Component Label = new Component(JavaDemo, "Label");

        /** "TreeBtn" Component in "JavaDemo". */
        public static final Component TreeBtn = new Component(JavaDemo, "TreeBtn");

        /** "Btn" Component in "JavaDemo". */
        public static final Component Btn = new Component(JavaDemo, "Btn");

        /** "MortBtn" Component in "JavaDemo". */
        public static final Component MortBtn = new Component(JavaDemo, "MortBtn");

        /** "Password" Component in "JavaDemo". */
        public static final Component Password = new Component(JavaDemo, "Password");

        /** "RadioBtn" Component in "JavaDemo". */
        public static final Component RadioBtn = new Component(JavaDemo, "RadioBtn");

        /** "ToggleBtn" Component in "JavaDemo". */
        public static final Component ToggleBtn = new Component(JavaDemo, "ToggleBtn");

        /** "TableBtn" Component in "JavaDemo". */
        public static final Component TableBtn = new Component(JavaDemo, "TableBtn");

        /** "Combobox" Component in "JavaDemo". */
        public static final Component Combobox = new Component(JavaDemo, "Combobox");

        /** "CheckBox" Component in "JavaDemo". */
        public static final Component CheckBox = new Component(JavaDemo, "CheckBox");

        /** "BascBtn" Component in "JavaDemo". */
        public static final Component BascBtn = new Component(JavaDemo, "BascBtn");
    }

    /** "SwingWindow" Component and its children. */
    public static class SwingWindow {

        // No use for a default constructor.
        private SwingWindow(){}

        /** "SwingWindow" Window Component itself. */
        public static final Component SwingWindow = new Component("SwingWindow");

        /** "WeirdSecondThird" Component in "SwingWindow". */
        public static final Component WeirdSecondThird = new Component(SwingWindow, "WeirdSecondThird");

        /** "PWeird" Component in "SwingWindow". */
        public static final Component PWeird = new Component(SwingWindow, "PWeird");

        /** "ToolsJTable2Viewer" Component in "SwingWindow". */
        public static final Component ToolsJTable2Viewer = new Component(SwingWindow, "ToolsJTable2Viewer");

        /** "JavaTable" Component in "SwingWindow". */
        public static final Component JavaTable = new Component(SwingWindow, "JavaTable");

        /** "JavaTree" Component in "SwingWindow". */
        public static final Component JavaTree = new Component(SwingWindow, "JavaTree");

        /** "EditBox10" Component in "SwingWindow". */
        public static final Component EditBox10 = new Component(SwingWindow, "EditBox10");

        /** "TextAreaHScrollBar" Component in "SwingWindow". */
        public static final Component TextAreaHScrollBar = new Component(SwingWindow, "TextAreaHScrollBar");

        /** "JTree" Component in "SwingWindow". */
        public static final Component JTree = new Component(SwingWindow, "JTree");

        /** "PToolsPTreeViewer" Component in "SwingWindow". */
        public static final Component PToolsPTreeViewer = new Component(SwingWindow, "PToolsPTreeViewer");

        /** "ListHScrollBar" Component in "SwingWindow". */
        public static final Component ListHScrollBar = new Component(SwingWindow, "ListHScrollBar");

        /** "jButton1" Component in "SwingWindow". */
        public static final Component jButton1 = new Component(SwingWindow, "jButton1");

        /** "PopupMenu" Component in "SwingWindow". */
        public static final Component PopupMenu = new Component(SwingWindow, "PopupMenu");

        /** "Third" Component in "SwingWindow". */
        public static final Component Third = new Component(SwingWindow, "Third");

        /** "PToolsPTable4Viewer" Component in "SwingWindow". */
        public static final Component PToolsPTable4Viewer = new Component(SwingWindow, "PToolsPTable4Viewer");

        /** "PToolsPMortgageCalculator" Component in "SwingWindow". */
        public static final Component PToolsPMortgageCalculator = new Component(SwingWindow, "PToolsPMortgageCalculator");

        /** "ToolsBasicComponents" Component in "SwingWindow". */
        public static final Component ToolsBasicComponents = new Component(SwingWindow, "ToolsBasicComponents");

        /** "Sep_0" Component in "SwingWindow". */
        public static final Component Sep_0 = new Component(SwingWindow, "Sep_0");

        /** "jRadioButton1" Component in "SwingWindow". */
        public static final Component jRadioButton1 = new Component(SwingWindow, "jRadioButton1");

        /** "Weird" Component in "SwingWindow". */
        public static final Component Weird = new Component(SwingWindow, "Weird");

        /** "CellRendererPane" Component in "SwingWindow". */
        public static final Component CellRendererPane = new Component(SwingWindow, "CellRendererPane");

        /** "PToolsPTableViewer" Component in "SwingWindow". */
        public static final Component PToolsPTableViewer = new Component(SwingWindow, "PToolsPTableViewer");

        /** "PHelp" Component in "SwingWindow". */
        public static final Component PHelp = new Component(SwingWindow, "PHelp");

        /** "ToolsJTable4Viewer" Component in "SwingWindow". */
        public static final Component ToolsJTable4Viewer = new Component(SwingWindow, "ToolsJTable4Viewer");

        /** "PWeirdPCheckBox" Component in "SwingWindow". */
        public static final Component PWeirdPCheckBox = new Component(SwingWindow, "PWeirdPCheckBox");

        /** "Term" Component in "SwingWindow". */
        public static final Component Term = new Component(SwingWindow, "Term");

        /** "PToolsPTree2Viewer" Component in "SwingWindow". */
        public static final Component PToolsPTree2Viewer = new Component(SwingWindow, "PToolsPTree2Viewer");

        /** "MonthlyPayment" Component in "SwingWindow". */
        public static final Component MonthlyPayment = new Component(SwingWindow, "MonthlyPayment");

        /** "EditBox" Component in "SwingWindow". */
        public static final Component EditBox = new Component(SwingWindow, "EditBox");

        /** "TabControl" Component in "SwingWindow". */
        public static final Component TabControl = new Component(SwingWindow, "TabControl");

        /** "ToolsJTree2Viewer" Component in "SwingWindow". */
        public static final Component ToolsJTree2Viewer = new Component(SwingWindow, "ToolsJTree2Viewer");

        /** "ScrollBar" Component in "SwingWindow". */
        public static final Component ScrollBar = new Component(SwingWindow, "ScrollBar");

        /** "HelpAbout" Component in "SwingWindow". */
        public static final Component HelpAbout = new Component(SwingWindow, "HelpAbout");

        /** "ToolsJTreeViewer" Component in "SwingWindow". */
        public static final Component ToolsJTreeViewer = new Component(SwingWindow, "ToolsJTreeViewer");

        /** "PToolsPPanelControls" Component in "SwingWindow". */
        public static final Component PToolsPPanelControls = new Component(SwingWindow, "PToolsPPanelControls");

        /** "ListBox" Component in "SwingWindow". */
        public static final Component ListBox = new Component(SwingWindow, "ListBox");

        /** "PTools" Component in "SwingWindow". */
        public static final Component PTools = new Component(SwingWindow, "PTools");

        /** "JPan" Component in "SwingWindow". */
        public static final Component JPan = new Component(SwingWindow, "JPan");

        /** "File" Component in "SwingWindow". */
        public static final Component File = new Component(SwingWindow, "File");

        /** "WeirdSecondFourth" Component in "SwingWindow". */
        public static final Component WeirdSecondFourth = new Component(SwingWindow, "WeirdSecondFourth");

        /** "JavaTable4" Component in "SwingWindow". */
        public static final Component JavaTable4 = new Component(SwingWindow, "JavaTable4");

        /** "JavaTable3" Component in "SwingWindow". */
        public static final Component JavaTable3 = new Component(SwingWindow, "JavaTable3");

        /** "preset" Component in "SwingWindow". */
        public static final Component preset = new Component(SwingWindow, "preset");

        /** "JavaTable2" Component in "SwingWindow". */
        public static final Component JavaTable2 = new Component(SwingWindow, "JavaTable2");

        /** "BascComp" Component in "SwingWindow". */
        public static final Component BascComp = new Component(SwingWindow, "BascComp");

        /** "ScrollBar2" Component in "SwingWindow". */
        public static final Component ScrollBar2 = new Component(SwingWindow, "ScrollBar2");

        /** "FileExit" Component in "SwingWindow". */
        public static final Component FileExit = new Component(SwingWindow, "FileExit");

        /** "JTree2" Component in "SwingWindow". */
        public static final Component JTree2 = new Component(SwingWindow, "JTree2");

        /** "ToolsJTableViewer" Component in "SwingWindow". */
        public static final Component ToolsJTableViewer = new Component(SwingWindow, "ToolsJTableViewer");

        /** "PercentInterestRate" Component in "SwingWindow". */
        public static final Component PercentInterestRate = new Component(SwingWindow, "PercentInterestRate");

        /** "PTools_Sep_0" Component in "SwingWindow". */
        public static final Component PTools_Sep_0 = new Component(SwingWindow, "PTools_Sep_0");

        /** "Tools" Component in "SwingWindow". */
        public static final Component Tools = new Component(SwingWindow, "Tools");

        /** "ComboBox" Component in "SwingWindow". */
        public static final Component ComboBox = new Component(SwingWindow, "ComboBox");

        /** "PWeirdPRadioButton" Component in "SwingWindow". */
        public static final Component PWeirdPRadioButton = new Component(SwingWindow, "PWeirdPRadioButton");

        /** "JavaPanel4" Component in "SwingWindow". */
        public static final Component JavaPanel4 = new Component(SwingWindow, "JavaPanel4");

        /** "JavaPanel3" Component in "SwingWindow". */
        public static final Component JavaPanel3 = new Component(SwingWindow, "JavaPanel3");

        /** "WeirdCheckBox" Component in "SwingWindow". */
        public static final Component WeirdCheckBox = new Component(SwingWindow, "WeirdCheckBox");

        /** "JavaPanel2" Component in "SwingWindow". */
        public static final Component JavaPanel2 = new Component(SwingWindow, "JavaPanel2");

        /** "MyJLabel" Component in "SwingWindow". */
        public static final Component MyJLabel = new Component(SwingWindow, "MyJLabel");

        /** "Principal" Component in "SwingWindow". */
        public static final Component Principal = new Component(SwingWindow, "Principal");

        /** "jCheckBox1" Component in "SwingWindow". */
        public static final Component jCheckBox1 = new Component(SwingWindow, "jCheckBox1");

        /** "MortgageCalculatorForm" Component in "SwingWindow". */
        public static final Component MortgageCalculatorForm = new Component(SwingWindow, "MortgageCalculatorForm");

        /** "Submit" Component in "SwingWindow". */
        public static final Component Submit = new Component(SwingWindow, "Submit");

        /** "Help" Component in "SwingWindow". */
        public static final Component Help = new Component(SwingWindow, "Help");

        /** "ToolsJTable3Viewer" Component in "SwingWindow". */
        public static final Component ToolsJTable3Viewer = new Component(SwingWindow, "ToolsJTable3Viewer");

        /** "ToolsJPanelControls" Component in "SwingWindow". */
        public static final Component ToolsJPanelControls = new Component(SwingWindow, "ToolsJPanelControls");

        /** "MortCalc" Component in "SwingWindow". */
        public static final Component MortCalc = new Component(SwingWindow, "MortCalc");

        /** "EditBox9" Component in "SwingWindow". */
        public static final Component EditBox9 = new Component(SwingWindow, "EditBox9");

        /** "EditBox8" Component in "SwingWindow". */
        public static final Component EditBox8 = new Component(SwingWindow, "EditBox8");

        /** "EditBox7" Component in "SwingWindow". */
        public static final Component EditBox7 = new Component(SwingWindow, "EditBox7");

        /** "EditBox6" Component in "SwingWindow". */
        public static final Component EditBox6 = new Component(SwingWindow, "EditBox6");

        /** "EditBox5" Component in "SwingWindow". */
        public static final Component EditBox5 = new Component(SwingWindow, "EditBox5");

        /** "PToolsPTable2Viewer" Component in "SwingWindow". */
        public static final Component PToolsPTable2Viewer = new Component(SwingWindow, "PToolsPTable2Viewer");

        /** "EditBox4" Component in "SwingWindow". */
        public static final Component EditBox4 = new Component(SwingWindow, "EditBox4");

        /** "JavaTree2" Component in "SwingWindow". */
        public static final Component JavaTree2 = new Component(SwingWindow, "JavaTree2");

        /** "EditBox3" Component in "SwingWindow". */
        public static final Component EditBox3 = new Component(SwingWindow, "EditBox3");

        /** "JavaMenu" Component in "SwingWindow". */
        public static final Component JavaMenu = new Component(SwingWindow, "JavaMenu");

        /** "JToggleButton1" Component in "SwingWindow". */
        public static final Component JToggleButton1 = new Component(SwingWindow, "JToggleButton1");

        /** "EditBox2" Component in "SwingWindow". */
        public static final Component EditBox2 = new Component(SwingWindow, "EditBox2");

        /** "JTable" Component in "SwingWindow". */
        public static final Component JTable = new Component(SwingWindow, "JTable");

        /** "ToolBar" Component in "SwingWindow". */
        public static final Component ToolBar = new Component(SwingWindow, "ToolBar");

        /** "PFilePExit" Component in "SwingWindow". */
        public static final Component PFilePExit = new Component(SwingWindow, "PFilePExit");

        /** "RootPane" Component in "SwingWindow". */
        public static final Component RootPane = new Component(SwingWindow, "RootPane");

        /** "PHelpPAbout" Component in "SwingWindow". */
        public static final Component PHelpPAbout = new Component(SwingWindow, "PHelpPAbout");

        /** "JavaPanel" Component in "SwingWindow". */
        public static final Component JavaPanel = new Component(SwingWindow, "JavaPanel");

        /** "PToolsPBasicComponents" Component in "SwingWindow". */
        public static final Component PToolsPBasicComponents = new Component(SwingWindow, "PToolsPBasicComponents");

        /** "TextAreaVScrollBar" Component in "SwingWindow". */
        public static final Component TextAreaVScrollBar = new Component(SwingWindow, "TextAreaVScrollBar");

        /** "WeirdSecond" Component in "SwingWindow". */
        public static final Component WeirdSecond = new Component(SwingWindow, "WeirdSecond");

        /** "WeirdRadioButton" Component in "SwingWindow". */
        public static final Component WeirdRadioButton = new Component(SwingWindow, "WeirdRadioButton");

        /** "ListVScrollBar" Component in "SwingWindow". */
        public static final Component ListVScrollBar = new Component(SwingWindow, "ListVScrollBar");

        /** "PFile" Component in "SwingWindow". */
        public static final Component PFile = new Component(SwingWindow, "PFile");

        /** "ToolsMortgageCalculator" Component in "SwingWindow". */
        public static final Component ToolsMortgageCalculator = new Component(SwingWindow, "ToolsMortgageCalculator");
    }

    /** "W3CAlertPage" Component and its children. */
    public static class W3CAlertPage {

        // No use for a default constructor.
        private W3CAlertPage(){}

        /** "W3CAlertPage" Window Component itself. */
        public static final Component W3CAlertPage = new Component("W3CAlertPage");

        /** "Button" Component in "W3CAlertPage". */
        public static final Component Button = new Component(W3CAlertPage, "Button");
    }

    /** "Basc_ListBox" Component and its children. */
    public static class Basc_ListBox {

        // No use for a default constructor.
        private Basc_ListBox(){}

        /** "Basc_ListBox" Window Component itself. */
        public static final Component Basc_ListBox = new Component("Basc_ListBox");

        /** "FilteredAreasWithError" Component in "Basc_ListBox". */
        public static final Component FilteredAreasWithError = new Component(Basc_ListBox, "FilteredAreasWithError");

        /** "FilteredAreasWithWarning" Component in "Basc_ListBox". */
        public static final Component FilteredAreasWithWarning = new Component(Basc_ListBox, "FilteredAreasWithWarning");
    }

    /** "GoJSSamples" Component and its children. */
    public static class GoJSSamples {

        // No use for a default constructor.
        private GoJSSamples(){}

        /** "GoJSSamples" Window Component itself. */
        public static final Component GoJSSamples = new Component("GoJSSamples");

        /** "MenuPageFlow" Component in "GoJSSamples". */
        public static final Component MenuPageFlow = new Component(GoJSSamples, "MenuPageFlow");

        /** "Diagram" Component in "GoJSSamples". */
        public static final Component Diagram = new Component(GoJSSamples, "Diagram");

        /** "Palette" Component in "GoJSSamples". */
        public static final Component Palette = new Component(GoJSSamples, "Palette");
    }

    /** "InternalSecondPage" Component and its children. */
    public static class InternalSecondPage {

        // No use for a default constructor.
        private InternalSecondPage(){}

        /** "InternalSecondPage" Window Component itself. */
        public static final Component InternalSecondPage = new Component("InternalSecondPage");
    }

    /** "SASFolderService001" Component and its children. */
    public static class SASFolderService001 {

        // No use for a default constructor.
        private SASFolderService001(){}

        /** "SASFolderService001" Window Component itself. */
        public static final Component SASFolderService001 = new Component("SASFolderService001");

        /** "AuthFile" Component in "SASFolderService001". */
        public static final Component AuthFile = new Component(SASFolderService001, "AuthFile");

        /** "FolderServiceHeader" Component in "SASFolderService001". */
        public static final Component FolderServiceHeader = new Component(SASFolderService001, "FolderServiceHeader");

        /** "FolderServiceHeaderFile" Component in "SASFolderService001". */
        public static final Component FolderServiceHeaderFile = new Component(SASFolderService001, "FolderServiceHeaderFile");
    }

    /** "InternalTestLinkPage" Component and its children. */
    public static class InternalTestLinkPage {

        // No use for a default constructor.
        private InternalTestLinkPage(){}

        /** "InternalTestLinkPage" Window Component itself. */
        public static final Component InternalTestLinkPage = new Component("InternalTestLinkPage");

        /** "Link" Component in "InternalTestLinkPage". */
        public static final Component Link = new Component(InternalTestLinkPage, "Link");

        /** "Body" Component in "InternalTestLinkPage". */
        public static final Component Body = new Component(InternalTestLinkPage, "Body");
    }

    /** "SAPDemoPage" Component and its children. */
    public static class SAPDemoPage {

        // No use for a default constructor.
        private SAPDemoPage(){}

        /** "SAPDemoPage" Window Component itself. */
        public static final Component SAPDemoPage = new Component("SAPDemoPage");

        /** "ListViewItemFederated" Component in "SAPDemoPage". */
        public static final Component ListViewItemFederated = new Component(SAPDemoPage, "ListViewItemFederated");

        /** "Basc_ListBox" Component in "SAPDemoPage". */
        public static final Component Basc_ListBox = new Component(SAPDemoPage, "Basc_ListBox");

        /** "Basc_TextArea" Component in "SAPDemoPage". */
        public static final Component Basc_TextArea = new Component(SAPDemoPage, "Basc_TextArea");

        /** "Basc_Link" Component in "SAPDemoPage". */
        public static final Component Basc_Link = new Component(SAPDemoPage, "Basc_Link");

        /** "ListViewItemArizona" Component in "SAPDemoPage". */
        public static final Component ListViewItemArizona = new Component(SAPDemoPage, "ListViewItemArizona");

        /** "TabControl" Component in "SAPDemoPage". */
        public static final Component TabControl = new Component(SAPDemoPage, "TabControl");

        /** "JPan_Postcode" Component in "SAPDemoPage". */
        public static final Component JPan_Postcode = new Component(SAPDemoPage, "JPan_Postcode");

        /** "Basc_ComboBox" Component in "SAPDemoPage". */
        public static final Component Basc_ComboBox = new Component(SAPDemoPage, "Basc_ComboBox");

        /** "ListViewItem5" Component in "SAPDemoPage". */
        public static final Component ListViewItem5 = new Component(SAPDemoPage, "ListViewItem5");

        /** "Basc_Password" Component in "SAPDemoPage". */
        public static final Component Basc_Password = new Component(SAPDemoPage, "Basc_Password");

        /** "ListViewItem26" Component in "SAPDemoPage". */
        public static final Component ListViewItem26 = new Component(SAPDemoPage, "ListViewItem26");

        /** "JPan_LastName" Component in "SAPDemoPage". */
        public static final Component JPan_LastName = new Component(SAPDemoPage, "JPan_LastName");

        /** "MenuBar" Component in "SAPDemoPage". */
        public static final Component MenuBar = new Component(SAPDemoPage, "MenuBar");

        /** "Basc_Radio" Component in "SAPDemoPage". */
        public static final Component Basc_Radio = new Component(SAPDemoPage, "Basc_Radio");

        /** "JPan_Address_L" Component in "SAPDemoPage". */
        public static final Component JPan_Address_L = new Component(SAPDemoPage, "JPan_Address_L");

        /** "JPan_FirstName_L" Component in "SAPDemoPage". */
        public static final Component JPan_FirstName_L = new Component(SAPDemoPage, "JPan_FirstName_L");

        /** "Basc_Password_L" Component in "SAPDemoPage". */
        public static final Component Basc_Password_L = new Component(SAPDemoPage, "Basc_Password_L");

        /** "Basc_Input_L" Component in "SAPDemoPage". */
        public static final Component Basc_Input_L = new Component(SAPDemoPage, "Basc_Input_L");

        /** "MenuBasicComponentsItem" Component in "SAPDemoPage". */
        public static final Component MenuBasicComponentsItem = new Component(SAPDemoPage, "MenuBasicComponentsItem");

        /** "Basc_CheckBox" Component in "SAPDemoPage". */
        public static final Component Basc_CheckBox = new Component(SAPDemoPage, "Basc_CheckBox");

        /** "TreeView" Component in "SAPDemoPage". */
        public static final Component TreeView = new Component(SAPDemoPage, "TreeView");

        /** "ListView" Component in "SAPDemoPage". */
        public static final Component ListView = new Component(SAPDemoPage, "ListView");

        /** "ListViewItemAlaska" Component in "SAPDemoPage". */
        public static final Component ListViewItemAlaska = new Component(SAPDemoPage, "ListViewItemAlaska");

        /** "MenuToolViewerItem" Component in "SAPDemoPage". */
        public static final Component MenuToolViewerItem = new Component(SAPDemoPage, "MenuToolViewerItem");

        /** "MenuToolsItem" Component in "SAPDemoPage". */
        public static final Component MenuToolsItem = new Component(SAPDemoPage, "MenuToolsItem");

        /** "ListViewItemAr" Component in "SAPDemoPage". */
        public static final Component ListViewItemAr = new Component(SAPDemoPage, "ListViewItemAr");

        /** "JPan_Postcode_L" Component in "SAPDemoPage". */
        public static final Component JPan_Postcode_L = new Component(SAPDemoPage, "JPan_Postcode_L");

        /** "JPan_Employee" Component in "SAPDemoPage". */
        public static final Component JPan_Employee = new Component(SAPDemoPage, "JPan_Employee");

        /** "JPan_Employee_L" Component in "SAPDemoPage". */
        public static final Component JPan_Employee_L = new Component(SAPDemoPage, "JPan_Employee_L");

        /** "JPan_LastName_L" Component in "SAPDemoPage". */
        public static final Component JPan_LastName_L = new Component(SAPDemoPage, "JPan_LastName_L");

        /** "JPan_FirstName" Component in "SAPDemoPage". */
        public static final Component JPan_FirstName = new Component(SAPDemoPage, "JPan_FirstName");

        /** "Basc_TextArea_L" Component in "SAPDemoPage". */
        public static final Component Basc_TextArea_L = new Component(SAPDemoPage, "Basc_TextArea_L");

        /** "Basc_Button" Component in "SAPDemoPage". */
        public static final Component Basc_Button = new Component(SAPDemoPage, "Basc_Button");

        /** "Basc_Input" Component in "SAPDemoPage". */
        public static final Component Basc_Input = new Component(SAPDemoPage, "Basc_Input");

        /** "JPan_Address" Component in "SAPDemoPage". */
        public static final Component JPan_Address = new Component(SAPDemoPage, "JPan_Address");

        /** "Basc_ToggleButton" Component in "SAPDemoPage". */
        public static final Component Basc_ToggleButton = new Component(SAPDemoPage, "Basc_ToggleButton");
    }

    /** "DynamicChart" Component and its children. */
    public static class DynamicChart {

        // No use for a default constructor.
        private DynamicChart(){}

        /** "DynamicChart" Window Component itself. */
        public static final Component DynamicChart = new Component("DynamicChart");

        /** "Serie1Btn" Component in "DynamicChart". */
        public static final Component Serie1Btn = new Component(DynamicChart, "Serie1Btn");

        /** "GridCheckBox" Component in "DynamicChart". */
        public static final Component GridCheckBox = new Component(DynamicChart, "GridCheckBox");

        /** "ComboBox" Component in "DynamicChart". */
        public static final Component ComboBox = new Component(DynamicChart, "ComboBox");

        /** "Serie5Btn" Component in "DynamicChart". */
        public static final Component Serie5Btn = new Component(DynamicChart, "Serie5Btn");

        /** "XCheckBox" Component in "DynamicChart". */
        public static final Component XCheckBox = new Component(DynamicChart, "XCheckBox");

        /** "YCheckBox" Component in "DynamicChart". */
        public static final Component YCheckBox = new Component(DynamicChart, "YCheckBox");
    }

    /** "W3CPage" Component and its children. */
    public static class W3CPage {

        // No use for a default constructor.
        private W3CPage(){}

        /** "W3CPage" Window Component itself. */
        public static final Component W3CPage = new Component("W3CPage");
    }
}
